### PR TITLE
Framework product name

### PR DESCRIPTION
**Pull request by mollidor**

### CODE REVIEW

**Comment by shagedorn** [comment]
@felixLam should re-visit this. The idea was to make linking HealthKit explicit as it has several implications (e.g., requiring a privacy policy).

**Comment by felixLam** [comment]
We already discussed this internally.

**Comment by felixLam** [comment]
The option to not use HealthKit is still present.

**Comment by mollidor** [comment]
Hang on guys, I will rebase that one once #24 is accepted. That should make the Travis light turn green.

**Pull request closed without merging**
