### PR TITLE
Link to sample app repository

### PR DESCRIPTION
**Pull request by shagedorn**
Please also take a look at:

https://github.com/iosphere/ISHPermissionKitSampleApp

### CODE REVIEW

**Comment by felixLam** [comment]
Should we delete the sample app from this repo or inlcude a weblink file?

**Comment by shagedorn** [comment]
The sample should have been deleted already.

**Comment by shagedorn** [comment]
Like the idea of a weblink file, for users that just check out the repo without reading the README (although sooner or later, they will have to read this file...)

**Comment by felixLam** [comment]
https://github.com/iosphere/ISHPermissionKit/tree/master/PermissionsTestApp

**Comment by shagedorn** [comment]
`master`

**Pull request merged**
